import { Animal } from "./types";

export const LEVEL_ANIMALS: Record<number, Animal[]> = {
  1: [
    {
      id: "monkey",
      name: "Jungle Monkey",
      emoji: "🐒",
      photoUrl: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=600&auto=format&fit=crop&q=80",
      funFact: "Monkeys are super smart! They use their long tails like a helper arm to swing between tall jungle trees. They love sweet yellow bananas!",
      word: "MAP",
      missingLetterIndex: 0,
      wrongLetters: ["T", "N"],
      sound: "mmm",
      blendedSound: "mmm ... aaah ... puh"
    },
    {
      id: "sloth",
      name: "Sleepy Sloth",
      emoji: "🦥",
      photoUrl: "https://images.unsplash.com/photo-1506531661544-cc62f1d3910c?w=600&auto=format&fit=crop&q=80",
      funFact: "Sloths are the slowest animals on earth! They spend almost their whole lives hanging upside down in green jungle trees eating leaves.",
      word: "BUG",
      missingLetterIndex: 0,
      wrongLetters: ["P", "S"],
      sound: "buh",
      blendedSound: "buh ... uuuh ... guh"
    },
    {
      id: "jaguar",
      name: "Spotted Jaguar",
      emoji: "🐆",
      photoUrl: "https://images.unsplash.com/photo-1575550959106-5a7defe28b56?w=600&auto=format&fit=crop&q=80",
      funFact: "Jaguars are beautiful big cats that love to swim in rivers! Most pet cats do not like water, but jaguars love splashing around!",
      word: "SUN",
      missingLetterIndex: 0,
      wrongLetters: ["M", "H"],
      sound: "sss",
      blendedSound: "sss ... uuuh ... nnn"
    },
    {
      id: "panda",
      name: "Fluffy Panda",
      emoji: "🐼",
      photoUrl: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=600&auto=format&fit=crop&q=80",
      funFact: "Giant pandas spend up to 12 hours every day munching on green bamboo! That is a lot of chewing for a furry bear!",
      word: "BAT",
      missingLetterIndex: 0,
      wrongLetters: ["W", "F"],
      sound: "buh",
      blendedSound: "buh ... aaah ... tuh"
    },
    {
      id: "squirrel",
      name: "Nutty Squirrel",
      emoji: "🐿️",
      photoUrl: "https://images.unsplash.com/photo-1507666480283-c21d1a0e22c6?w=600&auto=format&fit=crop&q=80",
      funFact: "Squirrels hide thousands of nuts in the soil, but they often forget where! Those forgotten nuts grow into brand new trees!",
      word: "NUT",
      missingLetterIndex: 0,
      wrongLetters: ["G", "L"],
      sound: "nnn",
      blendedSound: "nnn ... uuuh ... tuh"
    },
    {
      id: "hedgehog",
      name: "Prickly Hedgehog",
      emoji: "🦔",
      photoUrl: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=600&auto=format&fit=crop&q=80",
      funFact: "Hedgehogs have thousands of pointy prickles on their backs! When they get scared, they roll into a tight ball like a prickly bowling ball!",
      word: "DIG",
      missingLetterIndex: 0,
      wrongLetters: ["B", "M"],
      sound: "duh",
      blendedSound: "duh ... ihh ... guh"
    },
    {
      id: "tiger",
      name: "Striped Tiger",
      emoji: "🐅",
      photoUrl: "https://images.unsplash.com/photo-1508817628294-5a453fa0b8fb?w=600&auto=format&fit=crop&q=80",
      funFact: "Tigers are the biggest cats on Earth! No two tigers have the same stripes—their stripes are as unique as your fingerprints!",
      word: "CAT",
      missingLetterIndex: 0,
      wrongLetters: ["K", "P"],
      sound: "cuh",
      blendedSound: "cuh ... aaah ... tuh"
    },
    {
      id: "parrot",
      name: "Rainbow Parrot",
      emoji: "🦜",
      photoUrl: "https://images.unsplash.com/photo-1552728089-57bdde30ebd3?w=600&auto=format&fit=crop&q=80",
      funFact: "Parrots can talk! They mimic the sounds they hear and can copy human words perfectly to say hello!",
      word: "RED",
      missingLetterIndex: 0,
      wrongLetters: ["J", "W"],
      sound: "rrr",
      blendedSound: "rrr ... ehh ... duh"
    },
    {
      id: "frog",
      name: "Jumping Frog",
      emoji: "🐸",
      photoUrl: "https://images.unsplash.com/photo-1579383884351-4043b8118029?w=600&auto=format&fit=crop&q=80",
      funFact: "Frogs drink water through their skin instead of their mouths! Their skin is like a special drinking sponge.",
      word: "WET",
      missingLetterIndex: 0,
      wrongLetters: ["Z", "N"],
      sound: "wuh",
      blendedSound: "wuh ... ehh ... tuh"
    },
    {
      id: "bear",
      name: "Brown Bear",
      emoji: "🐻",
      photoUrl: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=600&auto=format&fit=crop&q=80",
      funFact: "Bears go into a deep sleep called hibernation during the snowy winter! They sleep through the cold without eating a single bite!",
      word: "LOG",
      missingLetterIndex: 0,
      wrongLetters: ["C", "S"],
      sound: "lll",
      blendedSound: "lll ... oooh ... guh"
    }
  ],
  2: [
    {
      id: "roadrunner",
      name: "Speedy Roadrunner",
      emoji: "🐦",
      photoUrl: "https://images.unsplash.com/photo-1614264669397-2a2ec96214bf?w=600&auto=format&fit=crop&q=80",
      funFact: "Roadrunners are very fast desert birds! They run up to twenty miles per hour across the warm dry sand, which is faster than you can ride a bicycle!",
      word: "JET",
      missingLetterIndex: 0,
      wrongLetters: ["W", "N"],
      sound: "juh",
      blendedSound: "juh ... ehh ... tuh"
    },
    {
      id: "fox",
      name: "Fennec Fox",
      emoji: "🦊",
      photoUrl: "https://images.unsplash.com/photo-1516642499105-492ff3ac521b?w=600&auto=format&fit=crop&q=80",
      funFact: "Fennec foxes have gigantic ears! Their huge ears act like fans to keep them cool in the desert and help them hear tiny bugs underground.",
      word: "FOX",
      missingLetterIndex: 0,
      wrongLetters: ["B", "P"],
      sound: "fff",
      blendedSound: "fff ... oxxx"
    },
    {
      id: "lizard",
      name: "Desert Lizard",
      emoji: "🦎",
      photoUrl: "https://images.unsplash.com/photo-1504450758481-7338eaa75e61?w=600&auto=format&fit=crop&q=80",
      funFact: "Desert lizards love to bake in the warm golden sun to get hyper active! Some can run so fast they look like they are dancing on the sand dunes.",
      word: "HOT",
      missingLetterIndex: 0,
      wrongLetters: ["L", "M"],
      sound: "huh",
      blendedSound: "huh ... oot ... tuh"
    },
    {
      id: "lion",
      name: "Roaring Lion",
      emoji: "🦁",
      photoUrl: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80",
      funFact: "A lion's loud roar can be heard from five miles away! It is like a super-sized megaphone shouting 'I am the King of the wild!'",
      word: "RUN",
      missingLetterIndex: 0,
      wrongLetters: ["M", "B"],
      sound: "rrr",
      blendedSound: "rrr ... uuuh ... nnn"
    },
    {
      id: "elephant",
      name: "Giant Elephant",
      emoji: "🐘",
      photoUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&auto=format&fit=crop&q=80",
      funFact: "Elephants use their long trunks like a combined arm, nose, and drinking straw! They use it to grab yummy leaves and spray water!",
      word: "TUB",
      missingLetterIndex: 0,
      wrongLetters: ["S", "N"],
      sound: "tuh",
      blendedSound: "tuh ... uuuh ... buh"
    },
    {
      id: "giraffe",
      name: "Tall Giraffe",
      emoji: "🦒",
      photoUrl: "https://images.unsplash.com/photo-1547721064-da6cfb341d50?w=600&auto=format&fit=crop&q=80",
      funFact: "Giraffes have blue tongues that are super long—up to 20 inches! They use them like fingers to carefully pull leaves off thorny branches.",
      word: "POT",
      missingLetterIndex: 0,
      wrongLetters: ["T", "G"],
      sound: "puh",
      blendedSound: "puh ... oooh ... tuh"
    },
    {
      id: "kangaroo",
      name: "Bouncy Kangaroo",
      emoji: "🦘",
      photoUrl: "https://images.unsplash.com/photo-1510797215324-95af89f79f44?w=600&auto=format&fit=crop&q=80",
      funFact: "Kangaroos cannot walk backward! They can only hop forward on their big, bouncy feet like a living, friendly pogo stick!",
      word: "BOX",
      missingLetterIndex: 0,
      wrongLetters: ["K", "F"],
      sound: "buh",
      blendedSound: "buh ... oxxx"
    },
    {
      id: "zebra",
      name: "Stripy Zebra",
      emoji: "🦓",
      photoUrl: "https://images.unsplash.com/photo-1501705388883-4ed8a543392c?w=600&auto=format&fit=crop&q=80",
      funFact: "Zebra stripes keep annoying biting flies away! The black and white patterns look like a crazy puzzle that dizzy flies hate to land on.",
      word: "SAD",
      missingLetterIndex: 0,
      wrongLetters: ["L", "Z"],
      sound: "sss",
      blendedSound: "sss ... aaah ... duh"
    },
    {
      id: "camel",
      name: "Humped Camel",
      emoji: "🐫",
      photoUrl: "https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?w=600&auto=format&fit=crop&q=80",
      funFact: "Camel humps do not hold water—they store fat! This fat gives camels plenty of energy when walking through the hot desert sand.",
      word: "CUP",
      missingLetterIndex: 0,
      wrongLetters: ["Q", "H"],
      sound: "cuh",
      blendedSound: "cuh ... uuuh ... puh"
    },
    {
      id: "meerkat",
      name: "Watchful Meerkat",
      emoji: "🦦",
      photoUrl: "https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?w=600&auto=format&fit=crop&q=80",
      funFact: "Meerkats take turns standing on their tiptoes as guards to watch for hawks while their friends search for sweet bugs!",
      word: "DIG",
      missingLetterIndex: 0,
      wrongLetters: ["G", "R"],
      sound: "duh",
      blendedSound: "duh ... ihh ... guh"
    }
  ],
  3: [
    {
      id: "dolphin",
      name: "Happy Dolphin",
      emoji: "🐬",
      photoUrl: "https://images.unsplash.com/photo-1570481662006-a3a1374699e8?w=600&auto=format&fit=crop&q=80",
      funFact: "Dolphins are super friendly sea mammals! They love to play, whistle, and click to talk to each other, and leap high out of the deep blue waves.",
      word: "FIN",
      missingLetterIndex: 0,
      wrongLetters: ["T", "G"],
      sound: "fff",
      blendedSound: "fff ... ihh ... nnn"
    },
    {
      id: "octopus",
      name: "Ninja Octopus",
      emoji: "🐙",
      photoUrl: "https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?w=600&auto=format&fit=crop&q=80",
      funFact: "Octopuses have three hearts and blue blood! They can change their skin color instantly like magic to hide in colorful coral reefs.",
      word: "RED",
      missingLetterIndex: 0,
      wrongLetters: ["D", "W"],
      sound: "rrr",
      blendedSound: "rrr ... ehh ... duh"
    },
    {
      id: "whale",
      name: "Giant Blue Whale",
      emoji: "🐋",
      photoUrl: "https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=600&auto=format&fit=crop&q=80",
      funFact: "Blue whales are the largest animals to ever live on Earth! They are even bigger than the biggest dinosaurs. Their heart is as big as a car!",
      word: "VAN",
      missingLetterIndex: 0,
      wrongLetters: ["K", "T"],
      sound: "vuh",
      blendedSound: "vuh ... aaah ... nnn"
    },
    {
      id: "penguin",
      name: "Chilly Penguin",
      emoji: "🐧",
      photoUrl: "https://images.unsplash.com/photo-1517783999520-f068d7431a60?w=600&auto=format&fit=crop&q=80",
      funFact: "Penguins are birds that swim instead of fly! They slide on their bellies across the cold, slippery ice like a mini sled!",
      word: "ZIP",
      missingLetterIndex: 0,
      wrongLetters: ["S", "H"],
      sound: "zzz",
      blendedSound: "zzz ... ihh ... puh"
    },
    {
      id: "turtle",
      name: "Sea Turtle",
      emoji: "🐢",
      photoUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
      funFact: "Sea turtles have been swimming in oceans since the dinosaur era! They travel thousands of miles and always find their way back home.",
      word: "MAP",
      missingLetterIndex: 0,
      wrongLetters: ["T", "F"],
      sound: "mmm",
      blendedSound: "mmm ... aaah ... puh"
    },
    {
      id: "otter",
      name: "Playful Sea Otter",
      emoji: "🦦",
      photoUrl: "https://images.unsplash.com/photo-1470115636472-88b43250f14d?w=600&auto=format&fit=crop&q=80",
      funFact: "Sea otters hold hands when they sleep so they do not drift apart in the ocean currents! How sweet is that?",
      word: "WET",
      missingLetterIndex: 0,
      wrongLetters: ["L", "V"],
      sound: "wuh",
      blendedSound: "wuh ... ehh ... tuh"
    },
    {
      id: "seal",
      name: "Spotted Seal",
      emoji: "🦭",
      photoUrl: "https://images.unsplash.com/photo-1520038410233-7141be7e6f97?w=600&auto=format&fit=crop&q=80",
      funFact: "Seals can sleep underwater! They close their noses tightly so no water gets in and hold their breath for up to two hours!",
      word: "MUG",
      missingLetterIndex: 0,
      wrongLetters: ["B", "N"],
      sound: "mmm",
      blendedSound: "mmm ... uuuh ... guh"
    },
    {
      id: "shark",
      name: "Friendly Shark",
      emoji: "🦈",
      photoUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&auto=format&fit=crop&q=80",
      funFact: "Sharks lose and replace thousands of teeth in their lifetime! When a tooth falls out, a new one slides forward like a conveyor belt!",
      word: "DOG",
      missingLetterIndex: 0,
      wrongLetters: ["S", "L"],
      sound: "duh",
      blendedSound: "duh ... oooh ... guh"
    },
    {
      id: "flamingo",
      name: "Pink Flamingo",
      emoji: "🦩",
      photoUrl: "https://images.unsplash.com/photo-1510525009512-ad7fc13eefab?w=600&auto=format&fit=crop&q=80",
      funFact: "Flamingos are pink because of the tiny shrimp they eat! When they sleep, they stand on just one leg to stay warm!",
      word: "PEN",
      missingLetterIndex: 0,
      wrongLetters: ["Z", "G"],
      sound: "puh",
      blendedSound: "puh ... ehh ... nnn"
    },
    {
      id: "starfish",
      name: "Sunny Starfish",
      emoji: "⭐",
      photoUrl: "https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?w=600&auto=format&fit=crop&q=80",
      funFact: "Starfish can regrow a lost arm if it gets hurt! Some can even grow an entire new body from just one single arm!",
      word: "SUN",
      missingLetterIndex: 0,
      wrongLetters: ["M", "B"],
      sound: "sss",
      blendedSound: "sss ... uuuh ... nnn"
    }
  ]
};
